name: torch
channels:
  - conda-forge
  - pytorch
  - defaults
  - nvidia

dependencies:
  - python=3.10
  - pytorch=2.4
  - torchvision
  - torchaudio
  - scikit-learn=1.3.0
  - pandas=2.2
  - numpy=1.26
  - scipy=1.14.0
  - matplotlib=3.9.2
  - pytorch-cuda=12.4
  - cudnn
  - pip:
      - reformer-pytorch
      - einops

